### ISSUE TITLE
Não tem lib fui enganado

### ISSUE THREAD

**Issue by MarcoWorms** [grvcoelho/lando#3]
kd

**Comment by joaolucasl** [comment]
![image](https://cloud.githubusercontent.com/assets/11381624/20583795/2f939962-b1d4-11e6-9e0d-0b032cb97f53.png)

**Comment by grvcoelho** [comment]
![image](https://cloud.githubusercontent.com/assets/7416751/20583984/a107ee4e-b1d5-11e6-94de-1fa57617a975.png)

**Comment by grvcoelho** [comment]
BTW, it's happening :tada:

**Comment by MarcoWorms** [comment]
TOTALLY NOT HAPPENING

**Comment by joaolucasl** [comment]
Logo, logo a gente canta parabéns pro meu PR: 
https://github.com/grvcoelho/lando/pull/12

**Comment by grvcoelho** [comment]
:tada: ANNOUNCEMENT :tada:

Sorry for the delay guys! We (the Lando Team™) have been very busy preparing to launch v1. Here's a detailed schedule of the release http://bit.ly/IqT6zt 💯 

🇧🇷 thanks for your support !!!1!

**Comment by MarcoWorms** [comment]
The Lando Team™™™™™™™™™™™™™™™™™™™™™™™™™™™™™™™
