### ISSUE TITLE
Use Symbols for placeholder

### ISSUE THREAD

**Issue by grvcoelho** [grvcoelho/lando#6]
## Description

ATM, we are using this as placeholder:

```javascript
const __ = {
  '@@functional/placeholder': true
}

const isPlaceholder = a => a['@@functional/placeholder']
```

## Proposal

We could use symbols for this instead:

```javascript
const __ = Symbol('@@functional/placeholder')

const isPlaceholder = a => a === __
```

What do you think of this approach, @joaolucasl?

cc: @derekstavis

**Comment by MarcoWorms** [comment]
Performance-wise they were equal in my benchmark. I think the Symbol approach looks nicer.

![screenshot from 2016-11-24 00-14-20](https://cloud.githubusercontent.com/assets/7863230/20584571/ff672752-b1da-11e6-9f2a-c2c2aa42f0bc.png)

**Comment by joaolucasl** [comment]
Yup, that's pretty much what symbols are for, aye?
